WIP: Bump CAPI to v1.9.z
kubernetes-sigs/cluster-api-provider-gcp pull request #1357
Opened 2024-11-06 11:19 UTC by damdo

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

CAPI v1.9.0-beta.0 is out now, so this PRs bumps the CAPI version used by CAPG to it.

Bumps CAPI to v1.9.z based on https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/developer/providers/migrations/v1.8-to-v1.9.md

**Special notes for your reviewer**:
api-diff failing is expected as the API changed to a typed go generics function.

**Checklist**:

- [x] squashed commits
- [x] adds or updates e2e tests

**Release note**:
```release-note
Bump CAPI to v1.9.z
```

2024-11-06 12:17 UTC, damdo commented
/test pull-cluster-api-provider-gcp-e2e-test

2024-11-07 17:35 UTC, damdo commented
TODO: try and add something like https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/85759ceebd3a679b599b2dd9ded48eb945fbdc28/test/e2e/shared/common.go#L68 in the AfterSuite of the e2e tests to dump details before the teardown.

2025-01-23 17:55 UTC, damdo commented
/test ?

2025-01-23 18:13 UTC, damdo commented
/test pull-cluster-api-provider-gcp-conformance
/test pull-cluster-api-provider-gcp-capi-e2e

2025-01-23 20:32 UTC, damdo commented
/assign @cpanato @richardcase @salasberryfin

2025-01-24 08:00 UTC, cpanato requested changes
a small nit

thanks for working on this

cc @justinsb

2025-01-24 08:00 UTC, cpanato commented on Makefile
> +GOLANG_VERSION := 1.22.8
1.22.11 use the latest as we already have in the dockerfile https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/Dockerfile#L16

2025-01-24 08:00 UTC, cpanato commented on Makefile
> +GOLANG_VERSION := 1.22.8
oh i think capi is using 1.23 but we can do that in a follow up

2025-01-24 08:02 UTC, damdo commented on Makefile
> +GOLANG_VERSION := 1.22.8
Updated to 1.22.11 thanks @cpanato

2025-01-24 08:06 UTC, cpanato approved these changes
thanks!

2025-01-24 08:16 UTC, damdo commented on Makefile
> +GOLANG_VERSION := 1.22.8
@cpanato BTW it looks like CAPI 1.9.4 is still using go 1.22 https://github.com/kubernetes-sigs/cluster-api/blob/79e6731b0d20a0ca2dad5e4f96d2a532aa82b54b/Makefile#L26

2025-01-24 08:17 UTC, salasberryfin approved these changes
Thanks @damdo

2025-01-24 08:43 UTC, merged