External provider
kubernetes-sigs/cluster-api-provider-gcp pull request #421
Opened 2021-09-23 17:00 UTC by sayantani11

**What type of PR is this?**

**What this PR does / why we need it**:
This PR adds tools and template for external provider
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
We would also have to add a file in the docs section related to the same
_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

2021-09-23 18:04 UTC, dims commented
/ok-to-test

2021-09-25 07:32 UTC, cpanato commented on CONTRIBUTING.md
> -# Contributing Guidelines
why removing the doc?

2021-09-25 07:38 UTC, cpanato requested changes
a few questions to clarify why we need this and how to use

2021-09-25 07:38 UTC, cpanato commented on templates/create_cloud_conf.sh
> +# Copyright 2020 The Kubernetes Authors.
usually, the scripts stay in the `script` directory

2021-09-25 07:38 UTC, cpanato commented on templates/create_cloud_conf.sh
> +CAPO_SCRIPT=create_cloud_conf.sh
why we define CAPO?

also this is not clear to me why we are adding this. can you give an explanation? maybe update the PR summary to add the reason we are adding this.

and add a readme to explain how to use that and what is the intent as well 

thanks so much!

2021-09-25 16:55 UTC, sayantani11 commented
@cpanato So we here we are trying to deploy a cluster using [external cloud provider](https://github.com/kubernetes/cloud-provider-gcp). And we will be using [this](https://docs.projectcalico.org/v3.19/manifests/calico.yaml) to deploy our CNI Solution. The `create_cloud_.sh` will basically be used to create the cloud secrets using this configurations and we can move that to the `scripts` folder as well. I do plan to add a README in the docs folder, but I am stuck as I am having problems in setting up the cluster locally. 
As of now we can move forward with the YAML file only. We can add the `.sh` file after I add the external-cloud-provider.md file to the docs. 
And concerning the `CONTRIBUTING.md` file, it was in a separate branch but somehow I messed up and it came here as well, so I had to remove it as this PR was not concerning this, seems like the file is getting deleted from the repo and I don't know how can I fix this🤦‍♀️

2021-09-25 17:42 UTC, sayantani11 commented
@cpanato If somehow you can ignore the `CONTRIBUTING.md` file from merging. My local branch is kind of corrupted and I am unable to remove it even after trying. It will be helpful of you can do it.

2021-10-01 23:48 UTC, closed without merging