Make cert manager install in makefile more resilient
kubernetes-sigs/cluster-api-provider-gcp pull request #481
Opened 2022-01-12 14:42 UTC by sayantani11

**What type of PR is this?**
This PR adds a cert manager installation script making the Makefile more resilient

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #480 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Addition of Cert Manager installation script
```

2022-01-13 05:19 UTC, sayantani11 commented
@cpanato

2022-01-15 17:05 UTC, sayantani11 commented
/test pull-cluster-api-provider-gcp-capi-e2e
/test pull-cluster-api-provider-gcp-conformance
/test pull-cluster-api-provider-gcp-conformance-ci-artifacts

2022-01-17 08:41 UTC, cpanato requested changes
thanks for that
just a small change

2022-01-17 08:41 UTC, cpanato commented on hack/install-cert-manager.sh
> +# Copyright 2021 The Kubernetes Authors.
```suggestion
# Copyright 2022 The Kubernetes Authors.
```

2022-01-18 10:21 UTC, cpanato commented
/test pull-cluster-api-provider-gcp-capi-e2e
/test pull-cluster-api-provider-gcp-conformance
/test pull-cluster-api-provider-gcp-conformance-ci-artifacts

2022-01-18 11:23 UTC, cpanato approved these changes
thanks!
/approve
/lgtm

2022-01-18 12:07 UTC, merged