Bash script added for shellcheck verification
kubernetes-sigs/cluster-api-provider-gcp pull request #483
Opened 2022-01-15 17:12 UTC by sayantani11

**What type of PR is this?**

**What this PR does / why we need it**:
This PR adds a bash script for shellcheck verification, and makes the changes required for the feature.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #482 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Shellcheck verfication script added
```

2022-01-15 19:01 UTC, mehabhalodiya reviewed
LGTM 🎉

2022-01-16 13:09 UTC, sayantani11 commented
/test pull-cluster-api-provider-gcp-capi-e2e
/test pull-cluster-api-provider-gcp-conformance
/test pull-cluster-api-provider-gcp-conformance-ci-artifacts

2022-01-16 14:38 UTC, sayantani11 commented
/test pull-cluster-api-provider-gcp-capi-e2e
/test pull-cluster-api-provider-gcp-conformance
/test pull-cluster-api-provider-gcp-conformance-ci-artifacts

2022-01-17 08:46 UTC, cpanato requested changes
thanks for that
a small request

2022-01-17 08:46 UTC, cpanato commented on hack/verify-shellcheck.sh
> +#Copyright 2018 The Kubernetes Authors.
```suggestion
# Copyright 2022 The Kubernetes Authors.
```

2022-01-17 14:58 UTC, cpanato approved these changes
thanks!
/approve
/lgtm

2022-01-17 14:59 UTC, merged