Typo in README.md #487
kubernetes-sigs/cluster-api-provider-gcp pull request #489
Opened 2022-01-21 05:10 UTC by KelvinEuclides

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note

```

2022-01-22 15:34 UTC, cpanato commented
@KelvinEuclides can you rebase your pr, please and fix the conflicts?

2022-01-22 15:34 UTC, cpanato commented
also need to sign the CLA

2022-01-28 17:55 UTC, jayesh-srivastava requested changes
I guess you shouldn't be leaving unnecessarily blank lines. What say?

2022-01-28 18:37 UTC, KelvinEuclides commented
Ok let me fix that real fast

2022-01-30 08:34 UTC, jayesh-srivastava requested changes
I guess you should 'squash' the commits into one. Three different commits for the same file aren't needed.

2022-01-30 08:35 UTC, jayesh-srivastava commented
Also, you need to sign the CLA before we can proceed further with the tests.

2022-02-07 04:58 UTC, sayantani11 commented
/release-note-none

2022-02-07 04:58 UTC, sayantani11 commented
Please sign the CLA

2022-02-07 08:04 UTC, cpanato commented on README.md
> +Although These issues have a smaller scope but are very helpful in getting acquainted with the codebase.
```suggestion
Although these issues have a smaller scope but are very helpful in getting acquainted with the codebase.
```

2022-02-07 09:27 UTC, KelvinEuclides commented
Good morning i have already signed both documents

2022-02-07 09:53 UTC, KelvinEuclides commented
![image](https://user-images.githubusercontent.com/20488304/152765198-b0148700-e568-4d96-aa80-35453489a815.png)

2022-02-13 13:01 UTC, cpanato commented
/easycla

2022-02-28 14:27 UTC, cpanato commented
/easycla

2022-02-28 15:19 UTC, sayantani11 commented
@KelvinEuclides 
```
7. My pull request still doesn't pass!
If you haven't yet, post a comment ("I signed it") to the PR—this is needed for the system to recheck your contribution authorization.

Each commit in the pull request needs to pass. If you have commits that didn't attribute to a Github username, or to a different user that hasn't signed the CLA, that will fail that commit and all subsequent commits.
```

2022-02-28 15:37 UTC, sayantani11 commented
@KelvinEuclides Just for the sake of it, can you also try "I signed it"

2022-02-28 15:38 UTC, KelvinEuclides commented
I signed it

On Mon, 28/02/2022 at 17:37 Sayantani Saha ***@***.***> wrote:

> @KelvinEuclides <https://github.com/KelvinEuclides> Just for the sake of
> it, can you also try "I signed it"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/489#issuecomment-1054381857>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE4KA4BCRVWUY375BLDHXT3U5OJEHANCNFSM5MOSIW2A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-28 16:39 UTC, jayesh-srivastava commented
@KelvinEuclides What @sayantani11 means to say is that you can just comment directly here the quote, I signed it , with double quotations marks. I guess that'll work.

2022-03-01 06:47 UTC, KelvinEuclides commented
"I signed it"

2022-03-01 08:09 UTC, cpanato reviewed
/ok-to-test

2022-03-04 16:16 UTC, sayantani11 commented
Hmm @KelvinEuclides Can you squash the commits?

2022-03-05 03:26 UTC, KelvinEuclides commented
Sorry ment to squash

On Sat, 5/03/2022 at 05:23 Kubernetes Prow Robot ***@***.***>
wrote:

> [APPROVALNOTIFIER] This PR is *NOT APPROVED*
>
> This pull-request has been approved by: *KelvinEuclides
> <https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/489#>*
> To complete the pull request process
> <https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process>,
> please assign *cecilerobertmichon* after the PR has been reviewed.
> You can assign the PR to them by writing /assign @cecilerobertmichon in a
> comment when ready.
>
> The full list of commands accepted by this bot can be found here
> <https://go.k8s.io/bot-commands?repo=kubernetes-sigs%2Fcluster-api-provider-gcp>
> .
> Needs approval from an approver in each of these files:
>
>    - *OWNERS
>    <https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/OWNERS>*
>
> Approvers can indicate their approval by writing /approve in a comment
> Approvers can cancel approval by writing /approve cancel in a comment
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/489#issuecomment-1059672577>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE4KA4CU4TELTUNT4LLYWSLU6LHURANCNFSM5MOSIW2A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-05 10:36 UTC, cpanato commented on README.md
> +Although These issues have a smaller scope but are very helpful in getting acquainted with the codebase.
@KelvinEuclides please review the comments and also squash the commits

2022-03-11 08:47 UTC, cpanato commented
/approve
/lgtm

2022-03-11 08:51 UTC, cpanato commented
humm sorry, just saw that it is still missing some changes

/lgtm cancel
/approve cancel

2022-03-11 08:51 UTC, cpanato commented on README.md
> +Although These issues have a smaller scope but are very helpful in getting acquainted with the codebase.
@KelvinEuclides gently ping on this

2022-07-08 15:41 UTC, richardcase commented
@KelvinEuclides - just checking in, any chance of squashing commits on this?

2022-07-27 08:05 UTC, cpanato commented
@KelvinEuclides gently ping to review the feedback and rebase.

2022-09-25 09:41 UTC, closed without merging