docs: Add Machine Pool flag reference to GKE enabling docs
kubernetes-sigs/cluster-api-provider-gcp pull request #880
Opened 2023-03-30 18:12 UTC by bubbaksmith

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Prior to this change, a user would get an error when trying to provision a quickstart GKE cluster with the current instructions. The error given from capg would instruct the user to enable the Machine Pool feature flag.

This change updates the readme for enabling capg with the GKE and Machine Pool feature flags and enables users to provision quickstart GKE clusters.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/879

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

2023-03-31 16:48 UTC, richardcase commented
/ok-to-test

2023-04-11 14:24 UTC, richardcase commented
@bubbaksmith - were you able to sort out the CLA?

2023-04-18 14:00 UTC, richardcase commented
/lgtm

2023-04-18 15:22 UTC, cpanato requested changes
thanks!
can you sign the CLA?

2023-04-21 14:54 UTC, bubbaksmith commented
Hey everyone. I am waiting on my employer to create the Linux Foundation Organization.

2023-05-11 06:51 UTC, richardcase commented
> Hey everyone. I am waiting on my employer to create the Linux Foundation Organization.

@bubbaksmith - any update on the CLA?

2024-03-19 05:46 UTC, closed without merging